### ISSUE TITLE
Cannot read property 'forEach' of undefined [BUG] 

### ISSUE THREAD

**Issue by dorianeydx** [tavicu/homebridge-samsung-tizen#102]
I installed Homebridge and this plugin following the README

```
~ $ homebridge 
[5/17/2019, 11:21:56 PM] Loaded config.json with 1 accessories and 2 platforms.
[5/17/2019, 11:21:56 PM] ---
[5/17/2019, 11:21:56 PM] Loaded plugin: homebridge-cmdswitch2
[5/17/2019, 11:21:56 PM] Registering platform 'homebridge-cmdswitch2.cmdSwitch2'
[5/17/2019, 11:21:56 PM] ---
[5/17/2019, 11:21:56 PM] Loaded plugin: homebridge-raspberrypi-temperature
[5/17/2019, 11:21:56 PM] Registering accessory 'homebridge-raspberrypi-temperature.RaspberryPiTemperature'
[5/17/2019, 11:21:56 PM] ---
[5/17/2019, 11:21:57 PM] Loaded plugin: homebridge-samsung-tizen
[5/17/2019, 11:21:57 PM] Registering platform 'homebridge-samsung-tizen.SamsungTizen'
[5/17/2019, 11:21:57 PM] ---
[5/17/2019, 11:21:57 PM] Loading 2 platforms...
[5/17/2019, 11:21:57 PM] [CMD Switch] Initializing cmdSwitch2 platform...
[5/17/2019, 11:21:57 PM] [SamsungTizen] Initializing SamsungTizen platform...
[5/17/2019, 11:21:58 PM] TypeError: Cannot read property 'forEach' of undefined
    at Accessory.createServices (/usr/lib/node_modules/homebridge-samsung-tizen/lib/accessory.js:33:37)
    at new Accessory (/usr/lib/node_modules/homebridge-samsung-tizen/lib/accessory.js:17:14)
    at new Device (/usr/lib/node_modules/homebridge-samsung-tizen/lib/device.js:22:30)
    at SamsungPlatform.accessories (/usr/lib/node_modules/homebridge-samsung-tizen/index.js:38:22)
    at Server._loadPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:403:20)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:341:16)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
[5/17/2019, 11:21:58 PM] Got SIGTERM, shutting down Homebridge...
~ $ 
```

**Versions:**
 - Node.js: 10.15.3
 - Homebridge: 0.4.49
 - Plugin: 3.1.1

(I used `npm list -g` because `npm -v <package>` return the npm version)

**Comment by Barloew** [comment]
I am getting the exact same error - with the exact same versions installed.

[5/17/2019, 11:54:25 PM] TypeError: Cannot read property 'forEach' of undefined
    at Accessory.createServices (/homebridge/node_modules/homebridge-samsung-tizen/lib/accessory.js:33:37)
    at new Accessory (/homebridge/node_modules/homebridge-samsung-tizen/lib/accessory.js:17:14)
    at new Device (/homebridge/node_modules/homebridge-samsung-tizen/lib/device.js:22:30)
    at SamsungPlatform.accessories (/homebridge/node_modules/homebridge-samsung-tizen/index.js:38:22)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:403:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:341:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
[5/17/2019, 11:54:25 PM] Got SIGTERM, shutting down Homebridge...

**Comment by monsterciattolo** [comment]
I have the same error message after the upgrade to latest version.

**Comment by tavicu** [comment]
Sorry for that! I have released a new version with the fix!

It was affecting users without custom switches!

**Comment by Barloew** [comment]
Thanks for the ultra quick review - and fix!
