### ISSUE TITLE
Compile Error in SamsungDevice.js

### ISSUE THREAD

**Issue by melyurt** [tavicu/homebridge-samsung-tizen#11]
When I start homebridge I got the error below.

[2018-8-27 21:39:29] Loaded plugin: homebridge-samsung-tizen
/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/SamsungDevice.js:52
                this.accessories.push(new SamsungAccessory({...this, config: {...this.config, ...element}}, 'switch'));
                                                            ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/SamsungPlatform.js:2:21)
pi@RaspberryHome:~ $

**Comment by tavicu** [comment]
Hi,

You need to update your nodejs

**Comment by melyurt** [comment]
Got it!!! Thanks for your help :)

**Comment by tavicu** [comment]
Let me know if it works after you update it :)

**Comment by robin1604** [comment]
what is the minimum version for Nodejs?
I have 8.2.1 and it is not working.
