### ISSUE TITLE
Device Not Shown to Pair - UN65NU7300

### ISSUE THREAD

**Issue by DennisFury** [tavicu/homebridge-samsung-tizen#113]
Model: UN65NU7300
Software Verson: T-KTM2LAKUC-1251.0

Device isn't showing up when trying to add as an accessory in Home app.

0|homebridge  | [2019-5-27 23:37:35] [SamsungTizen] Initializing SamsungTizen platform...
<about 5 seconds later, then>
0|homebridge  | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|homebridge  | TypeError: Cannot read property 'REWIND' of undefined
0|homebridge  |     at module.exports (/usr/lib/node_modules/homebridge-samsung-tizen/lib/options/remote.js:31:54)
0|homebridge  |     at new Television (/usr/lib/node_modules/homebridge-samsung-tizen/lib/services/television.js:8:55)
0|homebridge  |     at Accessory.createServices (/usr/lib/node_modules/homebridge-samsung-tizen/lib/accessory.js:23:37)
0|homebridge  |     at new Accessory (/usr/lib/node_modules/homebridge-samsung-tizen/lib/accessory.js:18:14)
0|homebridge  |     at new Device (/usr/lib/node_modules/homebridge-samsung-tizen/lib/device.js:29:26)
0|homebridge  |     at SamsungPlatform.init (/usr/lib/node_modules/homebridge-samsung-tizen/index.js:41:22)
0|homebridge  |     at <anonymous>

is this a new error?

going to the IP works
http://192.168.100.18:8001/api/v2/

and my config file looks like (MAC slightly edited for privacy)

"platforms": [
        {
        "platform": "SamsungTizen",
        "devices": [
            {
                "name": "Living Room TV",
                "ip": "192.168.100.18",
                "mac": "FC:03:9F:11:11:11"
            }
        ]
        },

**Comment by DennisFury** [comment]
This can be closed.

I updated homebridge with the following command (It's been 6+ months)

sudo npm install -g --unsafe-perm homebridge@latest

After updating, relaunching, TV started showing up.  Thanks
