### ISSUE TITLE
UE48Ju7590

### ISSUE THREAD

**Issue by flipse27** [tavicu/homebridge-samsung-tizen#118]
Good morning, just tried to setup these awesome plugin for my Samsung tv, but there is no pop-up upcoming on the display. I tried everything that is mentioned in your setup wiki, but nothing worked.
Can you please help me.
Homebridge just says:
```
[Livingroom TV] Opening handshake has timed out                                                                                                                         
[6/18/2019, 6:04:29 AM] [Livingroom TV] [DEBUG] SocketOpenError: Opening handshake has timed out                                                                                                
    at WebSocket._checkSocket (/homebridge/node_modules/homebridge-samsung-tizen/lib/methods/ws.js:151:19)                                                                                      
    at process._tickCallback (internal/process/next_tick.js:68:7)   
```

Can you please help me?

**Comment by tavicu** [comment]
Hi. The error means that the plugin can't connect to TV!

There are two possible issues here! One, your TV is not compatible. Second, somehow the homebridge server can't access the TV (blocked by firewall, or from router)
