### ISSUE TITLE
Node JS requirements 

### ISSUE THREAD

**Issue by LegendaryWiz** [tavicu/homebridge-samsung-tizen#135]
Hello, may I know what's the minimum Node JS requirements for this plugin? I have v8.2.1 for Node but I kept on running into errors for this plugin, while all of my other plugins are working fine.

Thank you ~

**Comment by tavicu** [comment]
Hi. Node 8 :)

Can you show us what errors?

**Comment by LegendaryWiz** [comment]
I got this errors : 

[2019-9-15 16:03:07] ====================
[2019-9-15 16:03:07] ERROR LOADING PLUGIN homebridge-samsung-tizen:
[2019-9-15 16:03:07] /usr/local/lib/node_modules/homebridge-samsung-tizen/lib/device.js:11
            ...platform.config,
            ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-samsung-tizen/index.js:2:15)
[2019-9-15 16:03:07] ====================
[2019-9-15 16:03:07] Loading 2 platforms...
[2019-9-15 16:03:07] Error: The requested platform 'SamsungTizen' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
[2019-9-15 16:03:07] Got SIGTERM, shutting down Homebridge...

**Comment by LegendaryWiz** [comment]
I've already tried upgrading Node JS with this command : 

curl -sL https://deb.nodesource.com/setup_8.x | sudo bash 
sudo apt-get install -y nodejs

It seems that it doesn't upgrade my Node JS since it's " already up to date " . Which is weird since I know v8.3.0 exist . The upgrade command runs smoothly without error but the node version still stays at v8.2.1 for my RPI

Is there any other troubleshooting that I can try ? Thank you very much

**Comment by tavicu** [comment]
What ‘node -v’ returns?

**Comment by LegendaryWiz** [comment]
It returns v8.2.1

**Comment by LegendaryWiz** [comment]
Alright, I've upgraded my Node to v8.3.0 . Now it works, plugin installed and running, TV added successfully. 

However I can't seem to turn the TV on form Home app, the log returns this: 

[2019-9-15 16:31:42] [TV] Failed to open socket {"data":{"update_type":"ed.installedApp.update"},"event":"ed.edenTV.update"}

Any idea what it means? I'm rather puzzled since turning off and other command works, just turning on isn't working.

Thank you !
