### ISSUE TITLE
Unable to start homebridge with samsung-tizen plugin

### ISSUE THREAD

**Issue by jaumebosch** [tavicu/homebridge-samsung-tizen#15]
Hi,
I've just installed homebridge and homebridge-samsung-tizen, and now I get this when starting
`root@raspberrypi:/home/pi# homebridge 
[2018-10-28 21:58:19] Loaded config.json with 0 accessories and 1 platforms.
[2018-10-28 21:58:19] ---
[2018-10-28 21:58:19] Loaded plugin: homebridge-samsung-tizen
/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/SamsungDevice.js:52
                this.accessories.push(new SamsungAccessory({...this, config: {...this.config, ...element}}, 'switch'));
                                                            ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/SamsungPlatform.js:2:21)
root@raspberrypi:/home/pi# 
`

Any ideas?

thx

**Comment by tavicu** [comment]
Hi,

You need to update your node to a newer version

**Comment by jaumebosch** [comment]
Done! works!

Thanks!
