### ISSUE TITLE
Pairing with Samsung TV ( GQ65Q60RGTXZG) won't start

### ISSUE THREAD

**Issue by CarlMcCoy** [tavicu/homebridge-samsung-tizen#179]
Hi all,

I bought a new TV and wanted to use it with the Samsung Tizen plugin. Homebridge has been running for years with FHEM without any problems.
The installation was without problems. The versions of Homebridge, node js etc are all up to date.
If I powerup the TV and then Homebridge, the pairing does not start. In the debug log I notice a seemingly missing IP.

>[2020-2-12 21:04:24] [SamsungTizen] Initializing SamsungTizen platform...
[2020-2-12 21:04:24] Loading 0 accessories...
Server listening on: http://<ip>:8282
(node:685) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'REWIND' of undefined
    at module.exports (/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/options/remote.js:31:44)
    at new Television (/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/services/television.js:12:55)
    at Television.createServices (/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/accessories/television.js:28:37)
    at new Television (/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/accessories/television.js:23:14)
    at new Device (/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/device.js:36:13)
    at SamsungPlatform.init (/usr/local/lib/node_modules/homebridge-samsung-tizen/index.js:45:22)
(node:685) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:685) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

My config.json looks like this:
`{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "123-45-678"
    },
 
    "platforms": [{
            "platform": "FHEM",
            "name": "FHEM",
            "server": "fhem.fritz.box",
            "port": "8083",
            "ssl": true,
            "filter": "room=Homekit",
            "auth": {"user": "username", "pass": "password"}
        },
        {
            "platform": "SamsungTizen",
            "devices": [{
                "name": "TIZEN",
                "ip": "192.168.1.41",
                "mac": "ETHERNET MAC-ADRESS"
            }]
        }
    ],
 
    "accessories": []
}`

Do you have an idea what is going wrong or is the Samsung not compatible? I forgot to mention, my IP is a fixed one.
Best Regards

**Comment by CarlMcCoy** [comment]
Hi all,

I've checked everything again. The versions are all current.
I found an old ticket #92 where a similar error message was described. 
There, Tavicu had pointed to the current version of homebridge. 
So I installed everything over it again. Nothing has changed in the versions, but the reinstallation fixed the error. 
The pairing was started I could approve the request on TV and everything is fine ;) 
@Tavicu thanks for the plugin! Great work and thanks for the support from issue #92 ;-) 
Ticket can be closed.

Best Regards

Translated with www.DeepL.com/Translator (free version)
