### ISSUE TITLE
Homebridge crushes after installing the plugin 

### ISSUE THREAD

**Issue by Sstefyuk2004** [tavicu/homebridge-samsung-tizen#195]
I have problems with running the plugin cuz every time when I run it, homebridge crushes and tries to update the page. Here is the log: 

TypeError: Cannot read property 'log' of undefined
    at Request._callback (C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\@piets\homebridge-samsung-tizen\lib\services\volume.js:87:29)
    at self.callback (C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\@piets\homebridge-samsung-tizen\node_modules\request\request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.onRequestError (C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\@piets\homebridge-samsung-tizen\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:311:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Help me to solve the problem.

**Comment by tavicu** [comment]
Hi! Make sure you have the latest version of Homebridge.

Also make sure you have the minimum requirements: https://github.com/tavicu/homebridge-samsung-tizen/wiki/Installation#requirements-to-run-the-plugin
