### ISSUE TITLE
Error when trying to use 4.3.0

### ISSUE THREAD

**Issue by normanmaurer** [tavicu/homebridge-samsung-tizen#208]
After upgrading to 4.3.0 I see the following error when trying to start home bridge:

```
0|homebrid | [4/28/2020, 1:21:20 PM] ====================
0|homebrid | [4/28/2020, 1:21:20 PM] ERROR LOADING PLUGIN homebridge-samsung-tizen:
0|homebrid | [4/28/2020, 1:21:20 PM] /usr/local/lib/node_modules/homebridge-samsung-tizen/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
0|homebrid |       } catch {
0|homebrid |               ^
0|homebrid | SyntaxError: Unexpected token {
0|homebrid |     at createScript (vm.js:80:10)
0|homebrid |     at Object.runInThisContext (vm.js:139:10)
0|homebrid |     at Module._compile (module.js:617:28)
0|homebrid |     at Object.Module._extensions..js (module.js:664:10)
0|homebrid |     at Module.load (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
0|homebrid |     at tryModuleLoad (module.js:506:12)
0|homebrid |     at Function.Module._load (module.js:498:3)
0|homebrid |     at Module.require (module.js:597:17)
0|homebrid |     at require (internal/module.js:11:18)
0|homebrid |     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-samsung-tizen/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
0|homebrid |     at Module._compile (module.js:653:30)
0|homebrid |     at Object.Module._extensions..js (module.js:664:10)
0|homebrid |     at Module.load (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
0|homebrid |     at tryModuleLoad (module.js:506:12)
0|homebrid |     at Function.Module._load (module.js:498:3)
0|homebrid |     at Module.require (module.js:597:17)
0|homebrid |     at require (internal/module.js:11:18)
0|homebrid |     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-samsung-tizen/node_modules/fs-extra/lib/copy-sync/copy-sync.js:5:20)
0|homebrid |     at Module._compile (module.js:653:30)
0|homebrid |     at Object.Module._extensions..js (module.js:664:10)
0|homebrid |     at Module.load (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
0|homebrid |     at tryModuleLoad (module.js:506:12)
0|homebrid |     at Function.Module._load (module.js:498:3)
0|homebrid |     at Module.require (module.js:597:17)
0|homebrid |     at require (internal/module.js:11:18)
0|homebrid |     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-samsung-tizen/node_modules/fs-extra/lib/copy-sync/index.js:4:13)
0|homebrid |     at Module._compile (module.js:653:30)
0|homebrid |     at Object.Module._extensions..js (module.js:664:10)
0|homebrid |     at Module.load (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
0|homebrid |     at tryModuleLoad (module.js:506:12)
0|homebrid |     at Function.Module._load (module.js:498:3)
0|homebrid |     at Module.require (module.js:597:17)
0|homebrid |     at require (internal/module.js:11:18)
0|homebrid |     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-samsung-tizen/node_modules/fs-extra/lib/index.js:7:6)
0|homebrid |     at Module._compile (module.js:653:30)
0|homebrid |     at Object.Module._extensions..js (module.js:664:10)
0|homebrid |     at Module.load (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
0|homebrid |     at tryModuleLoad (module.js:506:12)
0|homebrid |     at Function.Module._load (module.js:498:3)
0|homebrid |     at Module.require (module.js:597:17)
0|homebrid |     at require (internal/module.js:11:18)
0|homebrid |     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/storage.js:2:12)
0|homebrid |     at Module._compile (module.js:653:30)
0|homebrid |     at Object.Module._extensions..js (module.js:664:10)
0|homebrid |     at Module.load (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
0|homebrid |     at tryModuleLoad (module.js:506:12)
0|homebrid |     at Function.Module._load (module.js:498:3)
0|homebrid |     at Module.require (module.js:597:17)
0|homebrid |     at require (internal/module.js:11:18)
0|homebrid |     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-samsung-tizen/index.js:3:15)
0|homebrid |     at Module._compile (module.js:653:30)
0|homebrid |     at Object.Module._extensions..js (module.js:664:10)
0|homebrid |     at Module.load (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
0|homebrid |     at tryModuleLoad (module.js:506:12)
0|homebrid |     at Function.Module._load (module.js:498:3)
0|homebrid |     at Module.require (module.js:597:17)
0|homebrid |     at require (internal/module.js:11:18)
0|homebrid |     at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:72:23)
0|homebrid |     at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:153:14)
0|homebrid |     at Array.forEach (<anonymous>:null:null)
0|homebrid |     at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:145:22)
0|homebrid |     at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:57:24)
0|homebrid |     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:32:16)
0|homebrid |     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
0|homebrid |     at Module._compile (module.js:653:30)
0|homebrid |     at Object.Module._extensions..js (module.js:664:10)
0|homebrid |     at Module.load (module.js:566:32)
0|homebrid |     at tryModuleLoad (module.js:506:12)
0|homebrid |     at Function.Module._load (module.js:498:3)
0|homebrid |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:75:21)
0|homebrid |     at Module._compile (module.js:653:30)
0|homebrid |     at Object.Module._extensions..js (module.js:664:10)
0|homebrid |     at Module.load (module.js:566:32)
0|homebrid |     at tryModuleLoad (module.js:506:12)
0|homebrid |     at Function.Module._load (module.js:498:3)
0|homebrid |     at Function.Module.runMain (module.js:694:10)
0|homebrid |     at startup (bootstrap_node.js:204:16)
0|homebrid |     at bootstrap_node.js:625:3
```

Rolling back to 4.2.1 fixes the problem

**Comment by tavicu** [comment]
Hi! looks like one of the packages that was updated is having a problem! I have downgrade it and pushed a new version. It should be ok now!

**Comment by normanmaurer** [comment]
@tavicu thanks for the quick turn-around. This works
