### ISSUE TITLE
UE48JU7000 doesnt want to pair

### ISSUE THREAD

**Issue by maxikoz** [tavicu/homebridge-samsung-tizen#225]
{
  "id": "uuid:213c29fb-6d2b-4dc9-8a60-0e833f5ed3d8",
  "name": "[TV] Samsung",
  "version": "2.0.25",
  "device": {
    "type": "Samsung SmartTV",
    "duid": "uuid:213c29fb-6d2b-4dc9-8a60-0e833f5ed3d8",
    "model": "15_HAWKM_UHD",
    "modelName": "UE48JU7000",
    "description": "Samsung DTV RCR",
    "networkType": "wireless",
    "ssid": "60:45:cb:18:72:bc",
    "ip": "192.168.1.29",
    "firmwareVersion": "Unknown",
    "name": "[TV] Samsung",
    "id": "uuid:213c29fb-6d2b-4dc9-8a60-0e833f5ed3d8",
    "udn": "uuid:213c29fb-6d2b-4dc9-8a60-0e833f5ed3d8",
    "resolution": "1920x1080",
    "countryCode": "RU",
    "msfVersion": "2.0.25",
    "smartHubAgreement": "true",
    "wifiMac": "FC:F1:36:6C:20:08",
    "developerMode": "0",
    "developerIP": ""
  },
  "type": "Samsung SmartTV",
  "uri": "http://192.168.1.29:8001/api/v2/"
}

[5/31/2020, 7:43:06 PM] [Samsung] [DEBUG] {
  event: 'ms.channel.connect',
  data: { id: 'cd5a13a0-a35d-11ea-9ae8-c37f4f3acb81', clients: [ [Object] ] }
}
[5/31/2020, 7:43:06 PM] [Samsung] [DEBUG] {
  method: 'ms.remote.control',
  params: {
    Cmd: 'Click',
    DataOfCmd: 'KEY_POWER',
    Option: false,
    TypeOfRemote: 'SendRemoteKey'
  }
}
[5/31/2020, 7:43:06 PM] [Samsung] [DEBUG] SocketResponseError: unrecognized method value : ms.remote.control
    at WebSocket.<anonymous> (/homebridge/node_modules/homebridge-samsung-tizen/lib/methods/ws.js:186:44)
    at WebSocket.emit (events.js:223:5)
    at Receiver.receiverOnMessage (/homebridge/node_modules/homebridge-samsung-tizen/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:223:5)
    at Receiver.dataMessage (/homebridge/node_modules/homebridge-samsung-tizen/node_modules/ws/lib/receiver.js:436:14)
    at Receiver.getData (/homebridge/node_modules/homebridge-samsung-tizen/node_modules/ws/lib/receiver.js:366:17)
    at Receiver.startLoop (/homebridge/node_modules/homebridge-samsung-tizen/node_modules/ws/lib/receiver.js:142:22)
    at Receiver._write (/homebridge/node_modules/homebridge-samsung-tizen/node_modules/ws/lib/receiver.js:77:10)
    at doWrite (_stream_writable.js:435:12)
    at writeOrBuffer (_stream_writable.js:419:5)
    at Receiver.Writable.write (_stream_writable.js:309:11)
    at Socket.socketOnData (/homebridge/node_modules/homebridge-samsung-tizen/node_modules/ws/lib/websocket.js:875:35)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23)

[5/31/2020, 7:43:06 PM] [Samsung] [DEBUG] {
  event: 'ms.error',
  data: { message: 'unrecognized method value : ms.remote.control' }
}

**Comment by tavicu** [comment]
Hi. Looks like your tv is not compatible with the plugin.

Is using different pairing method which is not available with this plugin
