### ISSUE TITLE
Can't receive token

### ISSUE THREAD

**Issue by Serjip** [tavicu/homebridge-samsung-tizen#23]
After clicking allow on tv pop up in log receive crash

```/usr/lib/node_modules/homebridge-samsung-tizen/lib/SamsungRemote.js:396
Dec 04 22:12:47 raspberrypi homebridge[28113]: if (data.token) {
Dec 04 22:12:47 raspberrypi homebridge[28113]: ^
Dec 04 22:12:47 raspberrypi homebridge[28113]: TypeError: Cannot read property 'token' of undefined
Dec 04 22:12:47 raspberrypi homebridge[28113]: at WebSocket.socket.on (/usr/lib/node_modules/homebridge-samsung-tizen/lib/SamsungRemote.js:396:26)
Dec 04 22:12:47 raspberrypi homebridge[28113]: at emitOne (events.js:116:13)
Dec 04 22:12:47 raspberrypi homebridge[28113]: at WebSocket.emit (events.js:211:7)
Dec 04 22:12:47 raspberrypi homebridge[28113]: at Receiver.receiverOnMessage (/usr/lib/node_modules/homebridge-samsung-tizen/node_modules/ws/lib/websocket.js:720:20)
Dec 04 22:12:47 raspberrypi homebridge[28113]: at emitOne (events.js:116:13)
Dec 04 22:12:47 raspberrypi homebridge[28113]: at Receiver.emit (events.js:211:7)
Dec 04 22:12:47 raspberrypi homebridge[28113]: at Receiver.dataMessage (/usr/lib/node_modules/homebridge-samsung-tizen/node_modules/ws/lib/receiver.js:414:14)
Dec 04 22:12:47 raspberrypi homebridge[28113]: at Receiver.getData (/usr/lib/node_modules/homebridge-samsung-tizen/node_modules/ws/lib/receiver.js:346:17)
Dec 04 22:12:47 raspberrypi homebridge[28113]: at Receiver.startLoop (/usr/lib/node_modules/homebridge-samsung-tizen/node_modules/ws/lib/receiver.js:133:22)
Dec 04 22:12:47 raspberrypi homebridge[28113]: at Receiver._write (/usr/lib/node_modules/homebridge-samsung-tizen/node_modules/ws/lib/receiver.js:69:10)```

**Comment by tavicu** [comment]
Can you access this address? What it returns? `http://TV_IP:8001/api/v2/`

**Comment by JonoHaysom** [comment]
Getting this error on boot of homebridge:

[05/12/2018, 00:08:27] [SamsungTizen] Initializing SamsungTizen platform...

/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/SamsungDevice.js:26
        if (!config.ip) throw new Error(`TV IP address is required for ${config['name']}`);
                              ^
Error: TV IP address is required for Config
    at new SamsungDevice (/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/SamsungDevice.js:26:31)
    at SamsungPlatform.accessories (/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/SamsungPlatform.js:33:22)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:386:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:330:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)


Dumpfrom TV:API

{"device":{"FrameTVSupport":"false","GamePadSupport":"true","ImeSyncedSupport":"true","OS":"Tizen","TokenAuthSupport":"true","VoiceSupport":"true","countryCode":"GB","description":"Samsung DTV RCR","developerIP":"0.0.0.0","developerMode":"0","duid":"uuid:2baae266-72bd-4bf5-95d0-d9d1d6008ecc","firmwareVersion":"Unknown","id":"uuid:2baae266-72bd-4bf5-95d0-d9d1d6008ecc","ip":"192.168.1.190","model":"17_KANTM_UHD","modelName":"QE65Q8CAM","name":"[TV] Samsung","networkType":"none","resolution":"3840x2160","smartHubAgreement":"true","type":"Samsung SmartTV","udn":"uuid:2baae266-72bd-4bf5-95d0-d9d1d6008ecc","wifiMac":"none"},"id":"uuid:2baae266-72bd-4bf5-95d0-d9d1d6008ecc","isSupport":"{\"DMP_DRM_PLAYREADY\":\"false\",\"DMP_DRM_WIDEVINE\":\"false\",\"DMP_available\":\"true\",\"EDEN_available\":\"true\",\"FrameTVSupport\":\"false\",\"ImeSyncedSupport\":\"true\",\"TokenAuthSupport\":\"true\",\"remote_available\":\"true\",\"remote_fourDirections\":\"true\",\"remote_touchPad\":\"true\",\"remote_voiceControl\":\"true\"}\n","name":"[TV] Samsung","remote":"1.0","type":"Samsung SmartTV","uri":"http://192.168.1.190:8001/api/v2/","version":"2.0.25"}

**Comment by JonoHaysom** [comment]
{
			"platform": "SamsungTizen",
			"devices": [{
					"name": "Livingroom TV",
					"ip": "192.168.1.190",
					"mac": "d8:e0:e1:6a:b9:0b"
				},

is my JSON config.. ive not got "token" there as im initialising for the first time.

**Comment by tavicu** [comment]
@JonoHaysom you have a problem in the config file.
Make sure you have all parentheses closed as in the example.

**Comment by tavicu** [comment]
Hi @JonoHaysom, the config file must be correct too, not only valid :)

Pay attention at devices that is also having a `[` before `{`.

You may have a problem in another part of the json file.

Try to look over here: https://github.com/tavicu/homebridge-samsung-tizen/issues/22

I am 100% that what you have is a config problem especially that you set the name to `Livingroom TV` and in the error is as `Config`

**Comment by JonoHaysom** [comment]
updated it to the match the one above @tavicu  and now get this:

[05/12/2018, 19:00:32] [TV] Trying to pair the TV

/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/SamsungRemote.js:306
                if (data.token) {
                         ^
TypeError: Cannot read property 'token' of undefined
    at WebSocket.socket.on (/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/SamsungRemote.js:306:26)
    at WebSocket.emit (events.js:182:13)
    at Receiver.receiverOnMessage (/usr/local/lib/node_modules/homebridge-samsung-tizen/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:182:13)
    at Receiver.dataMessage (/usr/local/lib/node_modules/homebridge-samsung-tizen/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/usr/local/lib/node_modules/homebridge-samsung-tizen/node_modules/ws/lib/receiver.js:346:17)
    at Receiver.startLoop (/usr/local/lib/node_modules/homebridge-samsung-tizen/node_modules/ws/lib/receiver.js:133:22)
    at Receiver._write (/usr/local/lib/node_modules/homebridge-samsung-tizen/node_modules/ws/lib/receiver.js:69:10)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)

**Comment by tavicu** [comment]
Start the HomeBridge in debug mode. You will find in README how to do it.
Also check if you TV is compatible. In the README you will also find how to do it.

And make sure you are on the latest firmware in TV.

**Comment by JonoHaysom** [comment]
have done that I get the same output. 

[05/12/2018, 19:06:57] [TV] Trying to pair the TV

/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/SamsungRemote.js:306
                if (data.token) {
                         ^
TypeError: Cannot read property 'token' of undefined
    at WebSocket.socket.on (/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/SamsungRemote.js:306:26)
    at WebSocket.emit (events.js:182:13)
    at Receiver.receiverOnMessage (/usr/local/lib/node_modules/homebridge-samsung-tizen/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:182:13)
    at Receiver.dataMessage (/usr/local/lib/node_modules/homebridge-samsung-tizen/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/usr/local/lib/node_modules/homebridge-samsung-tizen/node_modules/ws/lib/receiver.js:346:17)
    at Receiver.startLoop (/usr/local/lib/node_modules/homebridge-samsung-tizen/node_modules/ws/lib/receiver.js:133:22)
    at Receiver._write (/usr/local/lib/node_modules/homebridge-samsung-tizen/node_modules/ws/lib/receiver.js:69:10)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)

TV output from API:

**Comment by JonoHaysom** [comment]
Id be happy to have you remote in via any desk if you wanted to see it first hand

**Comment by tavicu** [comment]
@JonoHaysom Strange ... looks like your TV is not returning any info when you press "Allow".
I will get home in ~2 hours and will see then :)

**Comment by JonoHaysom** [comment]
@tavicu ready when. you are!

**Comment by Serjip** [comment]
Hi @tavicu, example of response tv GET request

`{
"device": {
"FrameTVSupport": "false",
"GamePadSupport": "true",
"ImeSyncedSupport": "true",
"OS": "Tizen",
"TokenAuthSupport": "true",
"VoiceSupport": "true",
"countryCode": "RU",
"description": "Samsung DTV RCR",
"developerIP": "0.0.0.0",
"developerMode": "0",
"duid": "uuid",
"firmwareVersion": "Unknown",
"id": "uuid",
"ip": "192.168.88.17",
"model": "17_KANTM_UHD_BASIC",
"modelName": "UE40MU6400",
"name": "[TV] Samsung 6 Series (40)",
"networkType": "wireless",
"resolution": "3840x2160",
"smartHubAgreement": "true",
"ssid": "ssid",
"type": "Samsung SmartTV",
"udn": "uuid",
"wifiMac": "AA:"
},
"id": "uuid",
"isSupport": "{\"DMP_DRM_PLAYREADY\":\"false\",\"DMP_DRM_WIDEVINE\":\"false\",\"DMP_available\":\"true\",\"EDEN_available\":\"true\",\"FrameTVSupport\":\"false\",\"ImeSyncedSupport\":\"true\",\"TokenAuthSupport\":\"true\",\"remote_available\":\"true\",\"remote_fourDirections\":\"true\",\"remote_touchPad\":\"true\",\"remote_voiceControl\":\"true\"}\n",
"name": "[TV] Samsung 6 Series (40)",
"remote": "1.0",
"type": "Samsung SmartTV",
"uri": "http://192.168.88.17:8001/api/v2/",
"version": "2.0.25"
}`

**Comment by Serjip** [comment]
Finally after going to Access Notification menu and switching access for application to off and enable again token was received in console. I believe it some bug in tizen api, because it quite unstable

**Comment by tavicu** [comment]
@Serjip glad i was able to help :)

@JonoHaysom i made a mistake in README, to start with debug mode run it with `-D` parameter, like this `DEBUG=* homebridge -D`

And lets see what it returns in console when you click Allow :)

**Comment by JonoHaysom** [comment]
@tavicu ok, ive got it working, after wiresharking it was an issue with upnp secure mode on the new routers. found the issue and the pings and auth are now flowing.. great stuff! hope it sticks!

one thing, there seems to be a delay in statefulness of the switch. if I turn it off via the home app the switch turns off instantly, if I trigger via Siri voice then there is a delay showing on the switch that I dot see with lights etc

**Comment by JonoHaysom** [comment]
@tavicu https://github.com/petealves/homebridge-samsung-smart-tv18 are you able to check his source code? he has a super fast updating status for the device (stateful) is it the same method you're using?

**Comment by tavicu** [comment]
@JonoHaysom They are actually using a much slower method.
I ping the IP which is very fast when on (~75ms) and when it's off it has the minimum 1 second timeout of system.

Their method is sending a request to TV which takes 2 seconds when it's OFF.

Anyway, i have implemented a timeout and now it will respond in less than 250ms :)
It will go with the next release, probably tomorrow.

I will close this Issue since it was resolved
