### ISSUE TITLE
"Opening handshake has timed out" on Samsung UE48JS8500 

### ISSUE THREAD

**Issue by JBChesh** [tavicu/homebridge-samsung-tizen#232]
Hi,

I have two Samsung TV's, one is six months old and works just fine with your Tizen plugin, but the other which is around 4 years old doesn't.  Initially I thought the issue was it's not a Tizen based TV, but after checking it is.

I have read various comments within the forum but been unable to find a solution.  The TV does not come up with authentication approval, although you can see if the TV is on or off.

Within the logs I get the below which doesn't seem to help much.

[6/21/2020, 7:41:30 PM] [Lounge TV] Opening handshake has timed out
[6/21/2020, 7:41:30 PM] [Lounge TV] [DEBUG] SocketOpenError: Opening handshake has timed out
    at WebSocket._checkSocket (C:\Users\Joel\AppData\Roaming\npm\node_modules\homebridge-samsung-tizen\lib\methods\ws.js:154:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by tavicu** [comment]
Not compatible. Is using old version of Tizen
