### ISSUE TITLE
TvOfflineError regardless of TV's actual state

### ISSUE THREAD

**Issue by pdiegmann** [tavicu/homebridge-samsung-tizen#238]
Hi, 

while the TV has worked for quite a while flawlessly, I haven't been able to get it to work after moving homebridge to docker. Interestingly, the plugin appears to be able to connect to the device, but doesn't get it's power state correctly. This is an extract of the log – starting with the plugin detecting the TV and asking to add it manually (although it's already added to Home). The following lines are triggered from me trying to turn it on/off via Home.

> [7/16/2020, 4:09:21 PM] TV is running on port 41491.
> [7/16/2020, 4:09:21 PM] Please add [TV] manually in Home app. Setup Code: XXX-XX-XXX
> [7/16/2020, 4:10:52 PM] [TV] TV is offline
> [7/16/2020, 4:10:52 PM] [TV] [DEBUG] TvOfflineError: TV is offline
>     at Object.set (/usr/lib/node_modules/homebridge-samsung-tizen/lib/options/switch.js:20:27)
>     at Switch.setSwitch (/usr/lib/node_modules/homebridge-samsung-tizen/lib/services/switch.js:63:17)
> [7/16/2020, 4:10:56 PM] [TV] Powering on is in progress
> [7/16/2020, 4:10:56 PM] [TV] [DEBUG] PoweringOnlineError: Powering on is in progress
>     at Remote._turnOff (/usr/lib/node_modules/homebridge-samsung-tizen/lib/remote.js:234:19)
>     at Remote.setActive (/usr/lib/node_modules/homebridge-samsung-tizen/lib/remote.js:74:24)
>     at Television.setActive (/usr/lib/node_modules/homebridge-samsung-tizen/lib/services/television.js:53:28)
>     at Active.emit (events.js:315:20)
>     at Active.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
>     at Active.Characteristic._this.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:651:12)
>     at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1437:24
>     at Array.forEach (<anonymous>)
>     at Accessory._this._handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1279:10)
>     at HAPServer.emit (events.js:315:20)
> [7/16/2020, 4:11:11 PM] [TV] TV is offline
> [7/16/2020, 4:11:11 PM] [TV] [DEBUG] TvOfflineError: TV is offline
>     at Object.set (/usr/lib/node_modules/homebridge-samsung-tizen/lib/options/switch.js:20:27)
>     at Switch.setSwitch (/usr/lib/node_modules/homebridge-samsung-tizen/lib/services/switch.js:63:17)
> [7/16/2020, 4:11:13 PM] [TV] [DEBUG] TvOfflineError: TV is offline
>     at /usr/lib/node_modules/homebridge-samsung-tizen/lib/services/television.js:103:23
> [7/16/2020, 4:13:15 PM] [TV] TV is offline
> [7/16/2020, 4:13:15 PM] [TV] [DEBUG] TvOfflineError: TV is offline
>     at Object.set (/usr/lib/node_modules/homebridge-samsung-tizen/lib/options/switch.js:20:27)
>     at Switch.setSwitch (/usr/lib/node_modules/homebridge-samsung-tizen/lib/services/switch.js:63:17)

Any idea, what's going on here? This is my configuration for the TV:
```
"name": "TV",
"ip": "192.168.2.118",
"mac": "XX:...:XX",
"refresh": 10,
"keys": {
	"INFORMATION": "KEY_HOME"
}
```

Thank you for your help!

**Comment by pdiegmann** [comment]
Got it. Was an internal DNS resolution error in the IP subset.
