### ISSUE TITLE
Samsung Frame 2020

### ISSUE THREAD

**Issue by meaterator** [tavicu/homebridge-samsung-tizen#239]
Hi,

I have one Samsung Frame 2019, which works perfectly with the homebridge-samsung-tizen plug-in. Then, I have 4 Samsung Frame 2020 models and none of them work with it. They all say:
**Cannot read property 'forEach' of null**

After trying to determine if my TVs are compatible, they do show the info at the TV IP API page. Can you tell me if there is a trick to get this to work? Maybe a different plugin?

Thanks,
Aaron

**Comment by tavicu** [comment]
Hi! I don't have a 2020 model to test but i guess something changed in the API.

Can you help me with more details? when the error appears there are also the files and line where it happened.

That will be a start to see what info does it try to parse.

Thanks

**Comment by lovozeto** [comment]
Hi! I have a 2020 Samsung Q60 55” TV.
I’m using Hoobs and Homebridge to test out the differences. In both cases when I turn set:
`"app_list": true `
 I get:
`[QLED TV] Cannot read property 'forEach' of null `

**Comment by ecrode** [comment]
I'm having the same issues with Q7D from costco.

Homebridge to TV:
GET /api/v2/channels/samsung.remote.control?name=VFY= HTTP/1.1
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: +FBel7f0F4qjtw9bPFajhg==
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Host: 10.0.20.193:8002

TV to homebridge:
HTTP/1.1 101 Switching Protocols
Upgrade: WebSocket
Connection: Upgrade
Sec-WebSocket-Accept: we5rGAhKxhf8/IpflSQX2SFM98Q=

TV to homebridge: 
{"event":"ms.channel.timeOut"}

Error log shows:
[8/15/2020, 10:47:37 PM] [TV] [DEBUG] { event: 'ms.channel.timeOut' }
[8/15/2020, 10:47:37 PM] [TV] [DEBUG] Failed to open socket {"event":"ms.channel.timeOut"}
[8/15/2020, 10:47:38 PM] [TV] [DEBUG] { event: 'ms.channel.timeOut' }
[8/15/2020, 10:47:38 PM] [TV] [DEBUG] Failed to open socket {"event":"ms.channel.timeOut"}
[8/15/2020, 10:47:38 PM] [TV] Failed to pair! Make sure TV is online and you click "Allow" on the popup
[8/15/2020, 10:47:38 PM] [TV] [DEBUG] PairFailedError: Failed to pair! Make sure TV is online and you click "Allow" on the popup
    at WebSocketSecure.pair (/usr/lib/node_modules/homebridge-samsung-tizen/lib/methods/wss.js:34:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by tavicu** [comment]
I have fixed the forEach error but looks like with the newer version of tv's (2020) they removed or changed the api ...
