### ISSUE TITLE
Failure on start

### ISSUE THREAD

**Issue by Serjip** [tavicu/homebridge-samsung-tizen#254]
After update to version 4.3.3 homebrdige is crashing on launch. 4.3.2 is ok.

```
Sep 26 12:47:00 raspberrypi homebridge[3369]: [2020-9-26 12:47:00] ERROR LOADING PLUGIN homebridge-samsung-tizen:
Sep 26 12:47:00 raspberrypi homebridge[3369]: [2020-9-26 12:47:00] /usr/lib/node_modules/homebridge-samsung-tizen/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
Sep 26 12:47:00 raspberrypi homebridge[3369]: } catch {
Sep 26 12:47:00 raspberrypi homebridge[3369]: ^
Sep 26 12:47:00 raspberrypi homebridge[3369]: SyntaxError: Unexpected token {
Sep 26 12:47:00 raspberrypi homebridge[3369]: at createScript (vm.js:80:10)
Sep 26 12:47:00 raspberrypi homebridge[3369]: at Object.runInThisContext (vm.js:139:10)
Sep 26 12:47:00 raspberrypi homebridge[3369]: at Module._compile (module.js:617:28)
Sep 26 12:47:00 raspberrypi homebridge[3369]: at Object.Module._extensions..js (module.js:664:10)
Sep 26 12:47:00 raspberrypi homebridge[3369]: at Module.load (module.js:566:32)
Sep 26 12:47:00 raspberrypi homebridge[3369]: at tryModuleLoad (module.js:506:12)
Sep 26 12:47:00 raspberrypi homebridge[3369]: at Function.Module._load (module.js:498:3)
Sep 26 12:47:00 raspberrypi homebridge[3369]: at Module.require (module.js:597:17)
Sep 26 12:47:00 raspberrypi homebridge[3369]: at require (internal/module.js:11:18)
Sep 26 12:47:00 raspberrypi homebridge[3369]: at Object.<anonymous> (/usr/lib/node_modules/homebridge-samsung-tizen/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
Sep 26 12:47:00 raspberrypi homebridge[3369]: [2020-9-26 12:47:00] ====================
Sep 26 12:47:00 raspberrypi homebridge[3369]: [2020-9-26 12:47:00] Loaded plugin: homebridge-smartmi-humidifier
Sep 26 12:47:00 raspberrypi homebridge[3369]: [2020-9-26 12:47:00] Registering accessory 'homebridge-smartmi-humidifier.MiHumidifier'
Sep 26 12:47:00 raspberrypi homebridge[3369]: [2020-9-26 12:47:00] ---
Sep 26 12:47:02 raspberrypi homebridge[3369]: [2020-9-26 12:47:02] Error: The requested platform 'SamsungTizen' was not registered by any plugin.
Sep 26 12:47:02 raspberrypi homebridge[3369]: at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:134:13)
Sep 26 12:47:02 raspberrypi homebridge[3369]: at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:327:45)
Sep 26 12:47:02 raspberrypi homebridge[3369]: at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
Sep 26 12:47:02 raspberrypi homebridge[3369]: at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
Sep 26 12:47:02 raspberrypi homebridge[3369]: at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Sep 26 12:47:02 raspberrypi homebridge[3369]: at Module._compile (module.js:653:30)
Sep 26 12:47:02 raspberrypi homebridge[3369]: at Object.Module._extensions..js (module.js:664:10)
Sep 26 12:47:02 raspberrypi homebridge[3369]: at Module.load (module.js:566:32)
Sep 26 12:47:02 raspberrypi homebridge[3369]: at tryModuleLoad (module.js:506:12)
Sep 26 12:47:02 raspberrypi homebridge[3369]: at Function.Module._load (module.js:498:3)
```

**Comment by tavicu** [comment]
What version of node are you using?
