### ISSUE TITLE
Homebridge stop with refresh true

### ISSUE THREAD

**Issue by marithpl** [tavicu/homebridge-samsung-tizen#30]
Hi!

I’ve installed the new amazing update. But I have a problem with it. 
When I add refresh: true my Homebridge is broke and I recive this error:

“at process._tickCallback (internal/process/next_tick.js:180:9)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at endReadableNT (_stream_readable.js:1055:12)
    at IncomingMessage.emit (events.js:208:7)
    at emitNone (events.js:111:20)
    at Object.onceWrapper (events.js:313:30)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-samsung-tizen/node_modules/request/request.js:1083:12)
    at Request.emit (events.js:211:7)
    at emitOne (events.js:116:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-samsung-tizen/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:214:7)
    at emitTwo (events.js:126:13)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-samsung-tizen/node_modules/request/request.js:185:22)
    at Request.request.get [as _callback] (/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/SamsungRemote.js:237:37)
    at JSON.parse (<anonymous>)
SyntaxError: Unexpected token < in JSON at position 0
^
<html><body>401</body></html>
undefined:1”

Do you know a reason?

**Comment by tavicu** [comment]
Hei! I know the problem and has been fixed in the latest release.
Are you sure you are on the latest version? v2.1.2?

**Comment by marithpl** [comment]
Again Thanks! I

**Comment by marithpl** [comment]
Do you know spotify app id?

**Comment by tavicu** [comment]
@marithpl start the homebridge server with `homebridge tizen-apps` command and it will show you a table with all apps that are installed on TV.

Make sure your TV is paird and on.
