### ISSUE TITLE
Too much ping

### ISSUE THREAD

**Issue by NagyAttilaORG** [tavicu/homebridge-samsung-tizen#36]
Hello!

How can I change the ping time? As I see in my Logs the accessory ping my Tv too often. Can I change the frequency?

Thank you!

`  cmd: 'ping -t 1 -c 1 10.0.1.22' }
[12/16/2018, 12:00:26 PM] [Hálószoba TV] [DEBUG] PING 10.0.1.22 (10.0.1.22) 56(84) bytes of data.
--- 10.0.1.22 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms
[12/16/2018, 12:00:26 PM] [Hálószoba TV] [DEBUG] { Error: Command failed: ping -t 1 -c 1 10.0.1.22
    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'ping -t 1 -c 1 10.0.1.22' }
[12/16/2018, 12:00:36 PM] [Hálószoba TV] [DEBUG] PING 10.0.1.22 (10.0.1.22) 56(84) bytes of data.
--- 10.0.1.22 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms
[12/16/2018, 12:00:36 PM] [Hálószoba TV] [DEBUG] { Error: Command failed: ping -t 1 -c 1 10.0.1.22
    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'ping -t 1 -c 1 10.0.1.22' }`

**Comment by tavicu** [comment]
Set it to false and will ping every 10 seconds. In the next update you will be able to set a time in ms :)

I’ll keep you posted

**Comment by NagyAttilaORG** [comment]
Thank you tavicu!

That's what I call support! Now I give you a big STAR! :)
