### ISSUE TITLE
Can't upgrade to 5.1.0

### ISSUE THREAD

**Issue by twynne** [tavicu/homebridge-samsung-tizen#418]
Upgrade fails via ConfigUI and terminal with the following:

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/agent.js:114:44)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/index.js:5:33)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/make-fetch-happen/lib/agent.js:161:25)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)

**Comment by twynne** [comment]
Homebridge 1.3.4

Node.js Version	v16.6.1
Npm Version	v7.20.3

**Comment by tavicu** [comment]
Hi. 

The error you are showing is from a package that my plugin doesn't use. `socks-proxy-agent`

Other than suggesting to downgrade from node.js v16 to v14 i don't know what to say.
Node js v16 was released this year and many plugins did not upgraded yet to support it.
I suggest downgrading to v14 for this year until others starts to update their code for v16 which will became LTS (long term support) this year.
