### ISSUE TITLE
problem after adding tv to HK

### ISSUE THREAD

**Issue by Dorian-Grim** [tavicu/homebridge-samsung-tizen#476]
TV model:

- "model": "14_X14_BT"
- "modelName": "UE32H6400"
- "msfVersion": "2.0.24"
- "firmwareVersion": "Unknown"
- "type": "Samsung SmartTV"

What I did:

1. I installed the plugin in HB UI
2. in the plugin settings configured mac (got from router), UUID and IP, which I got from http://myTVip:8001/api/v2/
3. configured a switch with the name test, that changes channel to channel number 5
4. restarted HB. At one point I saw in the logs [2/17/2022, 10:43:11 AM] TVbedroom 9B5F is running on port 33879.
5. in HK I added tv as accessory and as a pin I put in my HB pin.
6. Accessory added (tv was on) so automatically in HK the accessory was set to ON state

What I did not do, it did not show any pop-up:

- https://github.com/tavicu/homebridge-samsung-tizen/wiki/Installation#5-pairing

Problem:

- the switch doesn't work. The channel doesn't change to 5
- can't turn the tv OFF while it's ON
- can't turn the tv ON while it's OFF
- if I toggle the ON/OFF button in HK, it automatically reverts to the real state of the TV. So if I turn the toggle OFF while the TV is ON, the toggle stays off for 5 seconds, then by itself turns back on (the real state of the tv).

**Comment by tavicu** [comment]
hi https://github.com/tavicu/homebridge-samsung-tizen/wiki/Common-Issues#how-to-open-a-new-issue

**Comment by Dorian-Grim** [comment]
`[2/17/2022, 6:26:34 PM] [TVbedroom] [DEBUG] 
  method: 'ms.remote.control',
  params: {
    Cmd: 'Click',
    DataOfCmd: 'KEY_POWER',
    Option: false,
    TypeOfRemote: 'SendRemoteKey'
  }
}`

`[2/17/2022, 6:26:34 PM] [TVbedroom] [DEBUG] {
  event: 'ms.channel.connect',
  data: { id: '77f54990-1dd8-11b2-ac90-055efe0be217', clients: [ [Object] ] }
}`

`[2/17/2022, 6:26:34 PM] [TVbedroom] [DEBUG] {
  event: 'ms.error',
  data: { message: 'unrecognized method value : ms.remote.control' }
}`

`[2/17/2022, 6:26:34 PM] [TVbedroom] [DEBUG] SocketResponseError: unrecognized method value : ms.remote.control
    at WebSocket.<anonymous> (/homebridge/node_modules/homebridge-samsung-tizen/lib/methods/ws.js:137:44)
    at WebSocket.emit (node:events:390:28)
    at Receiver.receiverOnMessage (/homebridge/node_modules/homebridge-samsung-tizen/node_modules/ws/lib/websocket.js:1137:20)
    at Receiver.emit (node:events:390:28)
    at Receiver.dataMessage (/homebridge/node_modules/homebridge-samsung-tizen/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/homebridge/node_modules/homebridge-samsung-tizen/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/homebridge/node_modules/homebridge-samsung-tizen/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/homebridge/node_modules/homebridge-samsung-tizen/node_modules/ws/lib/receiver.js:83:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)`

**Comment by tavicu** [comment]
From the error, your TV is not compatible with the plugin.
The TV it's an older generation which uses another API/method of pairing.

Unfortunately you need to search for another plugin which works with your TV.

I will use the logs you posted and in a future version will show an error message that the TV is not compatible.
