### ISSUE TITLE
keys don't work (TV UE55JU6500K)

### ISSUE THREAD

**Issue by TapsHTS** [tavicu/homebridge-samsung-tizen#531]
Hi ! I try to use your plugin to control my Samsung TV (UE55JU6500K) but when I use Remote App nothing happens.

```json
{
            "devices": [
                {
                    "name": "TV Home",
                    "ip": "192.168.1.38",
                    "mac": "FC:8F:--:--:--:2D",
                    "uuid": "A1",
                    "inputs": [
                        {
                            "type": "app",
                            "name": "Netflix",
                            "value": "11101200001"
                        },
                        {
                            "type": "app",
                            "name": "Youtube",
                            "value": "111299001912"
                        }
                    ],
                    "keys": {
                        "ARROW_UP": "KEY_UP",
                        "SELECT": "KEY_ENTER",
                        "INFORMATION": "KEY_HOME"
                    }
                }
            ],
            "platform": "SamsungTizen"
        }
```

**Comment by tavicu** [comment]
Hi,

You don't need to add `keys` to your config unless you want to change the default action for a button.

Regarding the problem, try to restart your phone. The problem is not from plugin/homebridge.

**Comment by TapsHTS** [comment]
Hi,

I turn on the debug mode and when i press a button, in the remote app, it return this error:

```
[14/06/2022, 22:20:40] [TV Salon] [DEBUG] {
  method: 'ms.remote.control',
  params: {
    Cmd: 'Click',
    DataOfCmd: 'KEY_RETURN',
    Option: false,
    TypeOfRemote: 'SendRemoteKey'
  }
}
[14/06/2022, 22:20:40] [TV Salon] [DEBUG] {
  event: 'ms.error',
  data: { message: 'unrecognized method value : ms.remote.control' }
}
[14/06/2022, 22:20:40] [TV Salon] [DEBUG] SocketResponseError: unrecognized method value : ms.remote.control
    at WebSocket.<anonymous> (/var/lib/homebridge/node_modules/.pnpm/homebridge-samsung-tizen@5.2.3/node_modules/homebridge-samsung-tizen/lib/methods/ws.js:111:44)
    at WebSocket.emit (node:events:527:28)
    at Receiver.receiverOnMessage (/var/lib/homebridge/node_modules/.pnpm/ws@8.2.3/node_modules/ws/lib/websocket.js:1022:20)
    at Receiver.emit (node:events:527:28)
    at Receiver.dataMessage (/var/lib/homebridge/node_modules/.pnpm/ws@8.2.3/node_modules/ws/lib/receiver.js:522:14)
    at Receiver.getData (/var/lib/homebridge/node_modules/.pnpm/ws@8.2.3/node_modules/ws/lib/receiver.js:440:17)
    at Receiver.startLoop (/var/lib/homebridge/node_modules/.pnpm/ws@8.2.3/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/var/lib/homebridge/node_modules/.pnpm/ws@8.2.3/node_modules/ws/lib/receiver.js:83:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
```

**Comment by tavicu** [comment]
What model your TV is?

**Comment by tavicu** [comment]
I don't think your TV is compatible with the plugin. From what I can see it's a 2015 model, thats the year when they released the "new" api that this plugin is using.

You can take a look over here to see how the menu should look in order to be the "new" os with the "new" api.
https://github.com/tavicu/homebridge-samsung-tizen/issues/406#issuecomment-917944872

**Comment by TapsHTS** [comment]
It's possible to change the os ?

**Comment by tavicu** [comment]
> It's possible to change the os ?

Unfortunately no


> or do u know a plugin compatible with my tv?

I didn't use another plugin myself since I have TVs after 2015 but others said this is an alternative: https://github.com/mmende/homebridge-samsungtv-control2#readme
