### ISSUE TITLE
i have some error

### ISSUE THREAD

**Issue by razvanu** [tavicu/homebridge-samsung-tizen#72]
Whrn trying to run it:

"platform": "SamsungTizen",
                        "deviceCfgs": [{
                                "name": "Livingroom TV",
                                "ip": "192.168.x.y",
                                "token": "",
                                "mac": "aa:bb:cc:dd:ee:ff"
                        }]

Loaded plugin: homebridge-samsung-tizen
/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/SamsungDevice.js:143
                this.accessories.push(new SamsungAccessory({...this, config: {...this.config, ...element}}, 'switch'));
                                                            ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/SamsungPlatform.js:2:21)

The syntax is correct, no err on https://jsonlint.com/

Can anyone help ? 10x

**Comment by chaingarden** [comment]
This may or may not solve the issue, but tavicu mentioned that you no longer need the “token” field in the JSON with this branch. It’s handled under the hood now.

**Comment by tavicu** [comment]
You need to update your node version! Also, it’s not deviceCfgs! Look in readme for examples!
