### ISSUE TITLE
Found a bug causing homebridge to crash

### ISSUE THREAD

**Issue by nitaybz** [tavicu/homebridge-samsung-tizen#76]
Hey...
after homebridge restart when the home app is open it always turn off the TV. i played a bit with the on off button and it created this crash:

```
Apr  3 21:43:41 raspberrypi homebridge[4003]: [4/3/2019, 9:43:41 PM] [Living Room TV] Failed to pair! Make sure TV is online and you click "Allow" on the popup
Apr  3 21:43:43 raspberrypi homebridge[4003]: /usr/lib/node_modules/homebridge-samsung-tizen/lib/methods/ws.js:149
Apr  3 21:43:43 raspberrypi homebridge[4003]: clearTimeout(this.socket.timeout);
Apr  3 21:43:43 raspberrypi homebridge[4003]: ^
Apr  3 21:43:43 raspberrypi homebridge[4003]: TypeError: Cannot read property 'timeout' of null
Apr  3 21:43:43 raspberrypi homebridge[4003]: at WebSocket.socket.ws.on.on (/usr/lib/node_modules/homebridge-samsung-tizen/lib/methods/ws.js:149:42)
Apr  3 21:43:43 raspberrypi homebridge[4003]: at WebSocket.emit (events.js:193:13)
Apr  3 21:43:43 raspberrypi homebridge[4003]: at WebSocket.emitClose (/usr/lib/node_modules/homebridge-samsung-tizen/node_modules/ws/lib/websocket.js:191:10)
Apr  3 21:43:43 raspberrypi homebridge[4003]: at TLSSocket.socketOnClose (/usr/lib/node_modules/homebridge-samsung-tizen/node_modules/ws/lib/websocket.js:850:15)
Apr  3 21:43:43 raspberrypi homebridge[4003]: at TLSSocket.emit (events.js:198:15)
Apr  3 21:43:43 raspberrypi homebridge[4003]: at _handle.close (net.js:614:12)
Apr  3 21:43:43 raspberrypi homebridge[4003]: at TCP.done (_tls_wrap.js:412:7)
```

**Comment by tavicu** [comment]
Pushed a patch. can you check please?
