### ISSUE TITLE
Homebridge crashes

### ISSUE THREAD

**Issue by k00d1** [tavicu/homebridge-samsung-tizen#9]
I'm having trouble with this plugin. It crashes my homebridge as soon as I start it up.

This is what I'm getting:
```
[2018-7-23 14:57:14] Loaded plugin: homebridge-samsung-tizen
/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/SamsungDevice.js:52
                this.accessories.push(new SamsungAccessory({...this, config: {...this.config, ...element}}, 'switch'));
                                                            ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/SamsungPlatform.js:2:21)
```

I validated my config with json formatter and honestly don't know what else to try. I've got my homebridge running on latest pi with latest raspbian OS.

**Comment by tavicu** [comment]
Hi,

What node and npm versions do you have? Try to update them.

**Comment by k00d1** [comment]
Updated:

node v8.2.1 -> 10.6.0
npm 6.1.0 -> 6.2.0

now getting this:
```
pi@pi:/var/lib/homebridge $ homebridge
/usr/local/lib/node_modules/homebridge/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: The module '/usr/local/lib/node_modules/homebridge/node_modules/ed25519-hap/build/Release/ed25519.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (/usr/local/lib/node_modules/homebridge/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/ed25519-hap/index.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)

```
I tried to install homebridge again and it's giving same error. Any ideas?

**Comment by tavicu** [comment]
What does `which npm` prints?

**Comment by k00d1** [comment]
/usr/local/bin/npm

**Comment by tavicu** [comment]
Try to remove the homebridge folder from /usr/local/lib/node_modules then install homebridge again.
`rm -rf /usr/local/lib/node_modules/homebridge`
`npm install -g --unsafe-perm homebridge`

I had the same problem when i updated nodejs but i don't remember how i fix it.
