### ISSUE TITLE
Homebridge not starting

### ISSUE THREAD

**Issue by eduspargoli** [tavicu/homebridge-samsung-tizen#92]
I'm trying to start homebridge with a simple code, but seems there is a type error:

Eduardos-MBP:~ eduspargoli$ DEBUG=* homebridge -D
[4/25/2019, 10:31:49 PM] Loaded config.json with 0 accessories and 1 platforms.
[4/25/2019, 10:31:49 PM] ---
[4/25/2019, 10:31:49 PM] Loaded plugin: homebridge-harmonyhub
[4/25/2019, 10:31:50 PM] Registering platform 'homebridge-harmonyhub.HarmonyHub'
[4/25/2019, 10:31:50 PM] ---
[4/25/2019, 10:31:50 PM] Loaded plugin: homebridge-samsung-tizen
[4/25/2019, 10:31:50 PM] Registering platform 'homebridge-samsung-tizen.SamsungTizen'
[4/25/2019, 10:31:50 PM] ---
[4/25/2019, 10:31:50 PM] Loading 1 platforms...
[4/25/2019, 10:31:50 PM] [SamsungTizen] Initializing SamsungTizen platform...
[4/25/2019, 10:31:50 PM] [SamsungTizen] Initializing platform accessory 'Samsung TV'...
/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/options/remote.js:32
        output[hap.Characteristic.RemoteKey[key]] = keys[key];
                                           ^

TypeError: Cannot read property 'REWIND' of undefined
    at module.exports (/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/options/remote.js:32:44)
    at new Television (/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/services/television.js:6:55)
    at Main.createMainService (/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/accessories/main.js:41:30)
    at Main.getServices (/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/accessories/main.js:32:14)
    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:410:36)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:396:32)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at SamsungPlatform.accessories (/usr/local/lib/node_modules/homebridge-samsung-tizen/index.js:48:9)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:386:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:330:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)

**Comment by tavicu** [comment]
Hi.

Make sure you have the latest version of Homebridge!

**Comment by eduspargoli** [comment]
Thanks!
